# Copyright 2026 Soltein SA. de CV.
# License LGPL-3 or later (http://www.gnu.org/licenses/lgpl.html)

{
    "name": "Website Common",
    "version": "18.0.1.0.2",
    "summary": "Soltein, Website",
    "category": "Soltein SA de CV/Website",
    "author": "Soltein SA de CV",
    "website": "https://soltein.mx",
    "license": "LGPL-3",
    "depends": ["website"],
    "data": [
        "views/res_company.xml",
        "views/res_config_settings_views.xml",
        "views/website.xml",
        "views/website_menu.xml",
        "data/upload_profile.xml",
        "security/ir_rule.xml",
        "security/ir.model.access.csv",
        "templates/status.xml",
        "views/upload_profile.xml",
        "templates/avatar.xml",
        "templates/portal.xml",
    ],
    "installable": True,
    "auto_install": False,
    "assets": {
        "website._assets_primary_variables": [],
        "web.assets_frontend": [
            "website_common/static/libs/echarts/echarts.min.js",
            "website_common/static/libs/colResizable-1.6.min.js",
            "website_common/static/libs/simplebar/simplebar.css",
            "website_common/static/libs/dragula/dragula.min.css",
            "website_common/static/libs/simplebar/simplebar.min.js",
            "website_common/static/libs/dragula/dragula.min.js",
            "website_common/static/src/scss/_mixins.scss",
            "website_common/static/src/scss/_function.scss",
            "website_common/static/src/scss/_avatar.scss",
            "website_common/static/src/scss/_banner.scss",
            "website_common/static/src/scss/_badges.scss",
            "website_common/static/src/scss/_navs.scss",
            "website_common/static/src/scss/_card.scss",
            "website_common/static/src/scss/_kanban.scss",
            "website_common/static/src/scss/_status.scss",
            "website_common/static/src/scss/_loading.scss",
            "website_common/static/src/scss/_portal.scss",
            "website_common/static/src/scss/_resize.scss",
            "website_common/static/src/xml/status.xml",
            "website_common/static/src/xml/tabs.xml",
            "website_common/static/src/js/utils/**/*",
            "website_common/static/src/js/filter-by-dropdown.js",
            "website_common/static/src/js/content/snippets.animation.js",
            "website_common/static/src/js/tabs.js",
            "website_common/static/src/js/status.js",
            "website_common/static/src/js/portal.js",
            "website_common/static/src/js/resize.js",
        ],
        "website_client.webclient": [
            "website_common/static/src/views/form/**/*",
        ],
        "web.assets_backend": [
            "website_common/static/src/js/rrule.js",
            "website_common/static/src/views/widgets/string_separated.xml",
            "website_common/static/src/views/widgets/string_separated.scss",
            "website_common/static/src/views/widgets/string_separated.js",
            "website_common/static/src/views/widgets/recursive_rule.xml",
            "website_common/static/src/views/widgets/recursive_rule.js",
            "website_common/static/src/views/fields/**/*",
        ],
        "web._assets_bootstrap_frontend": [
            (
                "after",
                "web/static/src/scss/utilities_custom.scss",
                "website_common/static/src/scss/_utilities.scss",
            ),
        ],
    },
}
